### ISSUE TITLE
[Web Tools]  adding new data button does not work on Model data listing section.

### ISSUE THREAD

**Issue by UlasSAYGINIM** [phpMv/ubiquity#132] opened 2020-07-15 12:34 UTC
### Steps
When model has 6 records,  then you refreshed page by clicking models.
if you want to add new records by clicking orange button Add New Models\... it does not show up form to add new records.

if you dont refresh model page, like you started adding new records to model which has less than 6 records, but didnt click models section to refresh the page after records number reach or exceed 6, you can continue to adding new records.

### Expected Result
we should be able to add new records.

### Actual Result

When you visit models page, and model has 6 records or more. it is like this.

![modelaccount_webtools_problem](https://user-images.githubusercontent.com/20348882/87545085-1e1d4580-c6b0-11ea-962b-da6fc27920a8.png)

When you visit, model that has no record you can add records as many as you like until you click model section to refresh the page, then you see same thing happening here.

![modelaccount_webtools_problem2](https://user-images.githubusercontent.com/20348882/87545094-1fe70900-c6b0-11ea-9231-e6d30963fece.png)

### Versions
- Ubiquity master-dev
- Ubiquity web tool master-dev
- php 7.x
- OS Win 10

**Comment by jcheron** [comment] 2020-07-15 12:59
On my side, I have a normal functioning, and I can't reproduce this bug.

If the loader remains displayed, it means that the status of the response is not 200, but there is a response anyway.
Could you display the network on the browser side, and display the contents of the response to see the error. ?

![image](https://user-images.githubusercontent.com/2511052/87547670-b95fec00-c6ab-11ea-90cf-b467e4dc4aba.png)

**Comment by UlasSAYGINIM** [comment] 2020-07-15 22:18
I created new project to test it. 
below is composer file. web and framework uses dev-master.
I just connected Postgresql db then create models and look the bug.

> `{
> 	"name" : "phpmv/ubiquity-project",
> 	"description" : "Ubiquity-framework new project",
> 	"type" : "framework",
> 	"keywords" : [
> 		"php",
> 		"framework",
> 		"mvc",
> 		"orm"
> 	],
> 	"require" : {
> 		"php" : "^7.4",
> 		"phpmv/ubiquity": "dev-master",
> 		"twig\/twig": "^3.0"
> 	},
> 	"license" : "Apache-2.0",
> 	"authors" : [{
> 			"name" : "Jean-Christophe HERON",
> 			"email" : "myaddressmail@gmail.com",
> 			"role" : "Lead developer"
> 		}
> 	],
> 	"autoload" : {
> 		"psr-4" : {
> 			"": "app/"
> 		}
> 	},
> 	"extra" : {
> 		"branch-alias" : {
> 			"dev-master" : "2.4.x-dev"
> 		}
> 	},
> 	"require-dev" : {
> 		"mindplay/annotations": "^1.3",
> 		"phpmv/ubiquity-devtools": "^1.2",
> 		"phpmv/ubiquity-webtools": "dev-master",
> 		"phpmv/ubiquity-codeception": "^1.0",
> 		"phpmv/php-mv-ui": "^2.2",
> 		"phpmv/ubiquity-dev": "^0.0",
> 		"phpmv/ubiquity-commands": "^0.0"
> 	},
> 	"minimum-stability": "dev",
> 	"prefer-stable": true,
> 	"scripts": {
> 		"post-create-project-cmd": [
> 			"@php vendor/phpmv/ubiquity-devtools/src/Ubiquity composer-create-project",
> 			"@php vendor/phpmv/ubiquity-devtools/src/Ubiquity init-cache"
> 		]
> 	}
> }
> `


![modelaccount_webtools_problem3](https://user-images.githubusercontent.com/20348882/87604646-218ced00-c701-11ea-9a37-1833c6cc3b98.png)

**Comment by UlasSAYGINIM** [comment] 2020-07-15 22:26
this is SQL file

[fpanel_20200716.zip](https://github.com/phpMv/ubiquity/files/4928278/fpanel_20200716.zip)

**Comment by jcheron** [comment] 2020-07-15 22:28
There are no bugs or error messages visible on your screen.
All requests return the code 200, right?

**Comment by UlasSAYGINIM** [comment] 2020-07-15 22:39
yes it seems so. it is mozilla, just i saw some of the css warnings but not sure it is effecting it or not. they seems just normal things.

I looked user model. it works without problem.

![modelaccount_webtools_problem4](https://user-images.githubusercontent.com/20348882/87607024-0d4aef00-c705-11ea-82c4-8230327b1a3f.png)

**Comment by UlasSAYGINIM** [comment] 2020-07-15 22:42
another screen shot. it seems 200 OK. no connection problem.

![modelaccount_webtools_problem5](https://user-images.githubusercontent.com/20348882/87607224-821e2900-c705-11ea-
8f8c-8784428718a5.png)

**Comment by UlasSAYGINIM** [comment] 2020-07-15 22:43
i think it is related to pagination and css.

**Comment by jcheron** [comment] 2020-07-15 23:08
Why don't you show the screenshot (and the response content) when the loader remains displayed, after inserting the 6 record?

**Comment by UlasSAYGINIM** [comment] 2020-07-15 23:21
firstly , open the page. here we start.

![modelaccount_webtools_problem6](https://user-images.githubusercontent.com/20348882/87609337-f14a4c00-c70a-11ea-8199-6c7f79567b93.png)

**Comment by UlasSAYGINIM** [comment] 2020-07-15 23:27
![modelaccount_webtools_problem7](https://user-images.githubusercontent.com/20348882/87609576-9b29d880-c70b-11ea-9323-408328c2cf98.png)

![modelaccount_webtools_problem8](https://user-images.githubusercontent.com/20348882/87609582-9cf39c00-c70b-11ea-8578-08ff4e8e8c8b.png)

![modelaccount_webtools_problem9](https://user-images.githubusercontent.com/20348882/87609687-e3e19180-c70b-11ea-9552-26f70c6a773c.png)

**Comment by jcheron** [comment] 2020-07-15 23:27
Okay, I saw
after the 6th record, the add or modify buttons don't display anything anymore, while the ajax request is well done

Is that right?

**Comment by UlasSAYGINIM** [comment] 2020-07-15 23:39
![modelaccount_webtools_problem11](https://user-images.githubusercontent.com/20348882/87610252-8f3f1600-c70d-11ea-83cc-32bd6b3fcf0e.png)
![modelaccount_webtools_problem12](https://user-images.githubusercontent.com/20348882/87610255-9108d980-c70d-11ea-8c45-113e76654f75.png)
![modelaccount_webtools_problem13](https://user-images.githubusercontent.com/20348882/87610258-936b3380-c70d-11ea-861c-f132ff014575.png)
![modelaccount_webtools_problem13](https://user-images.githubusercontent.com/20348882/87610263-97975100-c70d-11ea-9dac-a70171ef47a3.png)
![modelaccount_webtools_problem14](https://user-images.githubusercontent.com/20348882/87610267-99611480-c70d-11ea-8162-3cabb5b5bca8.png)
![modelaccount_webtools_problem15](https://user-images.githubusercontent.com/20348882/87610270-9b2ad800-c70d-11ea-8804-cb430295653c.png)
![modelaccount_webtools_problem16](https://user-images.githubusercontent.com/20348882/87610274-9c5c0500-c70d-11ea-9f20-0f9a64e157a6.png)

**Comment by UlasSAYGINIM** [comment] 2020-07-15 23:41
![modelaccount_webtools_problem11](https://user-images.githubusercontent.com/20348882/87610357-cf9e9400-c70d-11ea-89cd-64c4edb0ac1d.png)
![modelaccount_webtools_problem12](https://user-images.githubusercontent.com/20348882/87610358-d0372a80-c70d-11ea-9501-df46f5f6d727.png)
![modelaccount_webtools_problem13](https://user-images.githubusercontent.com/20348882/87610359-d0cfc100-c70d-11ea-9cbc-1bf851b5f744.png)
![modelaccount_webtools_problem14](https://user-images.githubusercontent.com/20348882/87610360-d0cfc100-c70d-11ea-892d-bde0329e0d2c.png)
![modelaccount_webtools_problem15](https://user-images.githubusercontent.com/20348882/87610361-d1685780-c70d-11ea-8b80-8ed952fc7ba7.png)
![modelaccount_webtools_problem16](https://user-images.githubusercontent.com/20348882/87610356-cf05fd80-c70d-11ea-9a1c-c8bcd7679ac1.png)

**Comment by UlasSAYGINIM** [comment] 2020-07-15 23:43
I deleted 6 records model into 5 nd i clicked the add new record button. deletion and add new record form show up screenshoots below.

![modelaccount_webtools_problem11](https://user-images.githubusercontent.com/20348882/87610407-f1981680-c70d-11ea-8e5d-80dc3e045568.png)
![modelaccount_webtools_problem12](https://user-images.githubusercontent.com/20348882/87610409-f1981680-c70d-11ea-9c32-4ce62ff3eb9e.png)
![modelaccount_webtools_problem13](https://user-images.githubusercontent.com/20348882/87610410-f230ad00-c70d-11ea-9e28-e69e8205ff4c.png)
![modelaccount_webtools_problem14](https://user-images.githubusercontent.com/20348882/87610412-f2c94380-c70d-11ea-8f94-9c80c34db81f.png)
![modelaccount_webtools_problem15](https://user-images.githubusercontent.com/20348882/87610414-f2c94380-c70d-11ea-83b7-7d2a3b020664.png)

![modelaccount_webtools_problem16](https://user-images.githubusercontent.com/20348882/87610404-f066e980-c70d-11ea-834b-12472bfc7240.png)

**Comment by UlasSAYGINIM** [comment] 2020-07-15 23:44
ajax request it ok. you are right.

**Comment by jcheron** [comment] 2020-07-15 23:45
Fixed in https://github.com/phpMv/ubiquity-webtools/commit/b5e2f7f20bfb7988e9593110ec52ee7e62366e8f ?

**Comment by UlasSAYGINIM** [comment] 2020-07-15 23:45
in order to get form, you need to look another page to refresh the models page, to show up the new record form.

**Comment by UlasSAYGINIM** [comment] 2020-07-15 23:49
Yes , Finally! but i have question that, why it is sometimes comes modal view and sometimes in embedded form?
can you make it one type?

![modelaccount_webtools_problem17_finally](https://user-images.githubusercontent.com/20348882/87610763-eb566a00-c70e-11ea-8844-f0e789864ff6.png)

**Comment by UlasSAYGINIM** [comment] 2020-07-15 23:51
it adds new records and no problem and continue to add new ones again. i tested both clicking to another model page and then come back and continuosly adding new ones. both ways seem ok.

**Comment by jcheron** [comment] 2020-07-16 00:06
> Yes , Finally! but i have question that, why it is sometimes comes modal view and sometimes in embedded form?
> can you make it one type?
By default, the form switches to modal beyond the 6th record in the table, but this can be changed ...

The administration can be customized, by modifying the Admin class generated by default, and by creating a ModelViewer class :
```php
namespace controllers;

use Ubiquity\controllers\admin\UbiquityMyAdminBaseController;
use controllers\admin\MyModelViewer;

class Admin extends UbiquityMyAdminBaseController {

	protected function getUbiquityMyAdminModelViewer() {
		return new MyModelViewer($this);
	}
}
```
Then create a ModelViewer class, and override the `isModal` method 
```php
namespace controllers\admin;

use Ubiquity\controllers\crud\viewers\ModelViewer;

class MyModelViewer extends ModelViewer {

	public function isModal($objects, $model) {
		// return \count ( $objects ) > 5;
		return false; //No more modal
	}
}
```

**Comment by UlasSAYGINIM** [comment] 2020-07-16 10:05
i thought that it related to css bug or strange behaviour. thank you for information. i think this bug is closed.
thank you for your help.

**Comment by UlasSAYGINIM** [comment] 2020-07-16 10:08
I would like to ask you something. when we add id number which has in database already, the database sfotware gives error about it. can you add feature like, if primary key is adding by manually, ubiquity checks it and if database has this primary key already and it warns it it. not shown exception thrown. can it be good idea?

**Comment by jcheron** [comment] 2020-07-16 13:29
If you are in debug mode (by default with the integrated php server), an exception is raised.
So you have to use a try/catch :
```php
try{
    $user=new User();
    $user->setId(1);
    DAO::insert($user);
catch(\Exception $e){
    //Do something with $e
}
```
If debug mode is inactive, no exceptions are thrown, but the insert will return false.
```php
$user=new User();
$user->setId(1);
if(!DAO::insert($user)){
      //no insert
}
```

**Comment by UlasSAYGINIM** [comment] 2020-07-16 18:28
Thank you!

**Closed** 2020-07-28 11:24 UTC
