### ISSUE TITLE
[ORM] How to build multiple join tables

### ISSUE THREAD

**Issue by danielbarenkamp** [phpMv/ubiquity#146] opened 2020-08-22 07:05 UTC
Hi there,

I am quite new to this framework and have basic question on how to build multiple join queries. 

1. Is it possible to execute custom queries with the DAO?
2. How can I best replicate this SQL query in ubiquity:

```
SELECT items.id, items.type, items.number, items.name, items.creator, items.year, items.files, GROUP_CONCAT(tags.name SEPARATOR ', ') as tags,  GROUP_CONCAT( DISTINCT( items2.name ) SEPARATOR ', ') as projects
FROM items 
LEFT  JOIN itemChildren ON itemChildren.itemId = items.id
LEFT  JOIN items items2 ON items2.id = itemChildren.childId
LEFT JOIN itemTags ON itemTags.itemId = items.id 
LEFT JOIN tags ON itemTags.tagId = tags.id

```

Hope someone can help me :) I would really like to understand this framework more as I think it is awesome!

**Comment by danielbarenkamp** [comment] 2020-08-24 08:54
Hmm does not seem to work as I get this error:

```
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM ``' at line 1 in /XXX/vendor/phpmv/ubiquity/src/Ubiquity/db/providers/pdo/PDOWrapper.php:195
Stack trace:
#0 /XXX/vendor/phpmv/ubiquity/src/Ubiquity/db/providers/pdo/PDOWrapper.php(195): PDOStatement->execute(NULL)
#1 /XXX/vendor/phpmv/ubiquity/src/Ubiquity/db/traits/DatabaseOperationsTrait.php(68): Ubiquity\db\providers\pdo\PDOWrapper->_optPrepareAndExecute('SELECT  FROM ``...', NULL)
#2 /XXX/vendor/phpmv/ubiquity/src/Ubiquity/orm/traits/DAOCoreTrait.php(124): Ubiquity\db\Database->prepareAndExecute(NULL, '', NULL, NULL, NULL)
#3 /XXX/vendor/phpmv/ubiquity/src/Ubiquity/orm/DAO.php(61): Ubiquity\orm\DAO::_getAll( in /XXX/vendor/phpmv/ubiquity/src/Ubiquity/db/providers/pdo/PDOWrapper.php on line 195

```

And it also does not generate the Table "itemTags" anymore in admin:

<img width="586" alt="Bildschirmfoto 2020-08-24 um 10 54 23" src="https://user-images.githubusercontent.com/3169388/91024420-36aa4500-e5f8-11ea-8c8e-fc37f8a60f85.png">
<img width="1001" alt="Bildschirmfoto 2020-08-24 um 10 53 45" src="https://user-images.githubusercontent.com/3169388/91024426-39a53580-e5f8-11ea-91e5-2b8320c8e8b2.png">

**Comment by jcheron** [comment] 2020-08-24 12:45
@danielbarenkamp 
can you provide the database creation script ?

**Comment by danielbarenkamp** [comment] 2020-08-24 13:14
@jcheron sure see here.
[d03344c1.sql.zip](https://github.com/phpMv/ubiquity/files/5118001/d03344c1.sql.zip)

**Comment by jcheron** [comment] 2020-08-24 13:47
for me, the generation is ok
It is normal that the model is not generated for the `itemTags` table, since it is an association table.
So you have a `ManyToMany` between Tags and Items.

![image](https://user-images.githubusercontent.com/2511052/91051298-3aea5880-e620-11ea-89fc-ae572c9b9b8d.png)

You have an inconsistency in your database, in the `ItemChildren` table, `itemId` should accept null values.

For your exception, you'd have to show me the line of code that produces this.

**Comment by danielbarenkamp** [comment] 2020-08-24 14:18
@jcheron hmm using the code you send. It can be that itemChildren is completly empty if there are no children. Maybe this causes the issue?

**Comment by jcheron** [comment] 2020-08-24 14:28
There is a bug in version 2.3.11 with the loading of associated objects (see https://github.com/phpMv/ubiquity/issues/145)
can you try on `dev-master`

`composer require phpmv/ubiquity:dev-master`

**Comment by danielbarenkamp** [comment] 2020-08-24 14:38
@jcheron same error. I can give you FTP access if ya need ...

**Comment by jcheron** [comment] 2020-08-24 14:45
no, it's better to give your code
`services.php`, `config.php`, the models, and the controller

**Comment by jcheron** [comment] 2020-08-24 14:52
Is the models cache up to date ?
maybe it needs to be regenerated
```
Ubiquity init-cache -t=models
```

**Comment by danielbarenkamp** [comment] 2020-08-24 15:06
Cleared, but still error ... 

See my app files (remove config login).

[app.zip](https://github.com/phpMv/ubiquity/files/5118668/app.zip)

**Comment by jcheron** [comment] 2020-08-24 15:17
In your `dashboard.php` controller file:
```php
$items=DAO::getAll(Item::class,'',true);
```
`Item` class does not exist
You mean `Items`

**Comment by danielbarenkamp** [comment] 2020-08-25 06:55
@jcheron what a dumb mistake :D Okay it works now 90% - great, but:

1) itemsChildren is not containing the "childId" (2 in this example) nor the item model with name etc. Your models admin page also misses the childId. Note: it is a self referencing field, so childId is ALSO an item.

<img width="755" alt="Bildschirmfoto 2020-08-25 um 08 53 37" src="https://user-images.githubusercontent.com/3169388/91142136-97955400-e6b0-11ea-9718-da3a3134c8a9.png">
<img width="512" alt="Bildschirmfoto 2020-08-25 um 08 51 36" src="https://user-images.githubusercontent.com/3169388/91142148-995f1780-e6b0-11ea-8316-d2ea719be0fd.png">
<img width="425" alt="Bildschirmfoto 2020-08-25 um 08 50 47" src="https://user-images.githubusercontent.com/3169388/91142149-99f7ae00-e6b0-11ea-8129-ec77107dd96b.png">


2) Is it possible to only get the "rest" stuff without the model + field name stuff?

3) I did not find something about pagination in your documentation? Do you have an example / may add this to your docs?

**Comment by danielbarenkamp** [comment] 2020-08-25 06:57
Oh and here a screen of the itemChildren model.

<img width="625" alt="Bildschirmfoto 2020-08-25 um 08 56 36" src="https://user-images.githubusercontent.com/3169388/91142354-ed69fc00-e6b0-11ea-8ebd-b2f5227287dd.png">

**Comment by jcheron** [comment] 2020-08-25 10:37
> 1. itemsChildren is not containing the "childId" (2 in this example) nor the item model with name etc. Your models admin page also misses the childId. Note: it is a self referencing field, so childId is ALSO an item.

you don't see the foreign keys in the administration's dataTable, but you can visualize the associated objects if you click on an instance. 
![image](https://user-images.githubusercontent.com/2511052/91163237-8ad32900-e6cd-11ea-805f-18da2185e9e0.png)

> 2. Is it possible to only get the "rest" stuff without the model + field name stuff?

`_rest` is a public member added at runtime, so you can do that:

```php
$user=DAO::getById(User::class,[1]);
$userToArray=$user->_rest;
```

> 3. I did not find something about pagination in your documentation? Do you have an example / may add this to your docs?

You have a `paginate` method on `DAO` class:

To access user page 2 (each page containing 10 users):
```php
$users=DAO::paginate(User::class,1,10);
```

### Note:
From a design point of view, I don't see what your `ItemChildren` table is for.
Each `ItemChildren` is associated with an `Item`.
An `ItemChildren` can have a parent, and can have many `ItemChildrens`.

I don't understand this complexity...
You want to take into account that each `Item` can have a parent item and children items?
In this case, it would have been enough to put an `idParent` field in reference to `Item.id` in the `Item` table, no ?

**Comment by danielbarenkamp** [comment] 2020-08-25 10:49
@jcheron 

1) Okay, but still the item is not in the "itemChildrens" array :( For your understanding this is needed because an item "product" can be in multiple item "projects". If I would only have 1 parent field in my items table, I could only assign 1 project to a product. 

2) Okay, but the subdata like "users" or "tags" need to be looped through also to only get rest data. Or is there something easier?

3) Ah great! Did not see it in your docs :)

**Comment by jcheron** [comment] 2020-08-25 10:56
> 1. Okay, but still the item is not in the "itemChildrens" array :( For your understanding this is needed because an item "product" can be in multiple item "projects". If I would only have 1 parent field in my items table, I could only assign 1 project to a product.

can you tell me exactly what data you want to get?

> 2. Okay, but the subdata like "users" or "tags" need to be looped through also to only get rest data. Or is there something easier?

Here again, I don't quite understand...

**Comment by danielbarenkamp** [comment] 2020-08-25 11:01
1) So Item 28 has item 2 as a child item and I need the data of item 2 inside the itemChildrens array. Same as tags do.

<img width="331" alt="Bildschirmfoto 2020-08-25 um 12 57 48" src="https://user-images.githubusercontent.com/3169388/91166407-9ffe8680-e6d2-11ea-8f91-044e976288d7.png">
<img width="415" alt="Bildschirmfoto 2020-08-25 um 12 57 44" src="https://user-images.githubusercontent.com/3169388/91166411-a12fb380-e6d2-11ea-880c-8f61f88f3a9b.png">

2) For example in the tags subarray I would also ONLY need the rest data:

<img width="343" alt="Bildschirmfoto 2020-08-25 um 13 00 07" src="https://user-images.githubusercontent.com/3169388/91166643-f66bc500-e6d2-11ea-9dea-9835e1fd29f0.png">

**Comment by jcheron** [comment] 2020-08-25 11:12
> 1. So Item 28 has item 2 as a child item and I need the data of item 2 inside the itemChildrens array. Same as tags do.

Something like that ?
```php
$item = DAO::getById(Items::class, 2, [
	'itemchildrens.items'
]);
$itemChildrens = $item->getItemChildrens();
foreach ($itemChildrens as $child) {
	var_dump($child->getItems());
}
```

**Comment by danielbarenkamp** [comment] 2020-08-25 11:16
@jcheron nope :/ Item 28 should contain itemChildrens with item data.

$items=DAO::getAll(Items::class,'',true);

**Comment by jcheron** [comment] 2020-08-25 11:25
no, the `included=true` allows the loading of associated objects, but not the cascading loading on associated objects.
So when you load an item, you load the itemChildrens, but not the associated objects of each itemChildren.

So you need to explicitly load what you need, for example by doing this: 
```php
$item=DAO::getById(Items::class, 2, ['itemchildrens.items']);
```
And there you have the items of each itemChildren of the loaded item.

**Comment by danielbarenkamp** [comment] 2020-08-26 08:36
@jcheron this does not work, itemChildren is still empty.

<img width="658" alt="Bildschirmfoto 2020-08-26 um 10 34 55" src="https://user-images.githubusercontent.com/3169388/91281140-04c7e880-e788-11ea-9208-30cdcf1827d5.png">

And also I do not want to loop through all items again, just to get the itemChildrens. Anyhow you may check my first question about my SQL query if that is possible.

**Comment by danielbarenkamp** [comment] 2020-08-26 09:23
Ah maybe I made a mistake by changing itemId with childId. It needs to be reverse like this:

<img width="494" alt="Bildschirmfoto 2020-08-26 um 11 21 48" src="https://user-images.githubusercontent.com/3169388/91286155-625f3380-e78e-11ea-89a8-8d6bc9261a25.png">

So "item 2" has 2 child items (products). However I still do not see the itemChilden in the array...

<img width="427" alt="Bildschirmfoto 2020-08-26 um 11 22 32" src="https://user-images.githubusercontent.com/3169388/91286240-7c991180-e78e-11ea-923d-938a32ff8944.png">

**Comment by jcheron** [comment] 2020-08-26 09:32
This is `itemChildrens`, with an `s`
And I can see it in your screenshot.

Otherwise, sorry to be insistent, but I am convinced that your data model is not valid.
I really don't see why the ItemChildren table is structured this way.

**Comment by danielbarenkamp** [comment] 2020-08-26 12:14
@jcheron still does not work ... to explain again: one product can be a chid of MULTIPLE projects. So just a "parent_id" field inside "items" table, would not allow multi assignments. 

BTW I would like to use "$items=DAO::getAll(Items::class,'',true);" and just get tags + itemChildren as items.

**Comment by jcheron** [comment] 2020-08-26 12:30
On your screenshot (https://github.com/phpMv/ubiquity/issues/146#issuecomment-680765882), it seems to work, you do have the ItemChildrens


a product is an Item
and a project is also an Item?

**Comment by danielbarenkamp** [comment] 2020-08-26 12:59
@jcheron in the screenshot you see that item with id 2 has childitems with id 2. That makes no sense ... it just has the same id in the itemChildren.

Yes both are items. ItemChildrens is the manyToMany connection.

**Comment by jcheron** [comment] 2020-08-26 13:12
In this case, the `ItemChildrens` table should be an association table with the fields
- `itemProduct` fk in reference to `Item.id`
- `itemProject` fk in reference to `item.id`

**Comment by danielbarenkamp** [comment] 2020-08-26 13:13
it is ...

<img width="1531" alt="Bildschirmfoto 2020-08-26 um 15 13 17" src="https://user-images.githubusercontent.com/3169388/91307776-acf0a800-e7ae-11ea-8d0a-3898bfb06f4b.png">

**Comment by jcheron** [comment] 2020-08-26 13:18
Not in the database you gave me,
foreign keys do not refer to Items.id
![image](https://user-images.githubusercontent.com/2511052/91308276-56d03480-e7af-11ea-957c-4ae1183c24b1.png)

and in addition there is a primary key id that should not exist

**Comment by danielbarenkamp** [comment] 2020-08-26 13:20
primary key is in the table.

See here sql file again. 

[d03344c1 (1).sql.zip](https://github.com/phpMv/ubiquity/files/5130030/d03344c1.1.sql.zip)

**Comment by jcheron** [comment] 2020-08-26 13:30
The base has changed since the previous sending...
Not easy to guess it if you don't say so

**Comment by jcheron** [comment] 2020-08-26 13:34
And why does this association table have a primary key `id`, when the primary key could have been `itemId`, `childId`?
Can you have several times the same couple (product/project)?

**Comment by danielbarenkamp** [comment] 2020-08-26 13:36
Yes of course an itemId can be 2 or multiple times in the itemChildren table. That is why there is primary key id.

**Comment by jcheron** [comment] 2020-08-26 13:42
So the couple `itemId/childId` is not unique in the `ItemChidrens` table?

**Comment by danielbarenkamp** [comment] 2020-08-26 14:02
the couple you mean both values as one right? Yes these are unique.

**Comment by jcheron** [comment] 2020-08-26 14:04
In this case, why is `itemId, childId` not the primary key of this association table?

**Comment by danielbarenkamp** [comment] 2020-08-26 14:25
what does this has to do with why it is not working? The itemTags also does not have this ...

**Comment by jcheron** [comment] 2020-08-26 14:37
Indeed, ItemTag is also badly structured

The problem probably comes from the fact that you have 2 associations between the same tables (2 times between Item and ItemChildren), and that the class generator didn't know how to handle that. 

In your class, you should have only one item member, whereas you should have two.

```php
	/**
	 * @manyToOne
	 * @joinColumn("className"=>"models\\Items","name"=>"childId","nullable"=>false)
	 * @manyToOne
	 * @joinColumn("className"=>"models\\Items","name"=>"itemId","nullable"=>false)
	**/
	private $items;
```
It should be that way:
```php
	/**
	 *
	 * @manyToOne
	 * @joinColumn("className"=>"models\\Items","name"=>"childId","nullable"=>false)
	 */
	private $oItems;

	/*
	 * @manyToOne
	 * @joinColumn("className"=>"models\\Items","name"=>"itemId","nullable"=>false)
	 */
	private $items;
```

**Comment by danielbarenkamp** [comment] 2020-08-26 15:45
<img width="399" alt="Bildschirmfoto 2020-08-26 um 17 44 08" src="https://user-images.githubusercontent.com/3169388/91325788-e41d8400-e7c3-11ea-86f3-eb9fc42096d8.png">

still empty.

**Comment by jcheron** [comment] 2020-08-26 15:54
Which line of code produces this result????
You show me null objects far enough in the tree...
If you go further than level 1, you have to explicitly include the associated objects to be loaded
```php
$item=DAO::getById(Item::class,[1],['itemChildren.oItems','itemChildren.items']);
//or $item=DAO::getById(Item::class,[1],['itemChildren.*']);
```

**Comment by danielbarenkamp** [comment] 2020-08-27 07:03
still does not work - I give up now. I think you have a good framework here when it comes to speed, but it is sad that this simple table query does not work. An option would be to allow custom queries https://laravel.com/docs/7.x/queries#raw-expressions

**Comment by jcheron** [comment] 2020-08-27 09:11
Hi @danielbarenkamp 
- You display results, without giving the context (including even the corresponding line of code!). It is therefore impossible to reproduce your problem.
- You don't answer my questions, and you don't take my answers into account.
- You don't listen to my advice when I tell you that your database is poorly structured. It is very rare to meet ManyToMany sef-referencing, and defined this way, ever.

It is therefore quite inappropriate to judge the framework in these conditions.

**Comment by jcheron** [comment] 2020-08-27 09:16
I close this issue which does not lead to any constructive results.

**Closed by jcheron** 2020-08-27 09:16 UTC
Labels: question
